In [1]:
import threading
import queue
import cProfile
import itertools
import numpy as np
np.random.seed(0)

In [2]:
in_queue = queue.Queue()
out_queue = queue.Queue()
def random_number_threading():
    while True:
        n = in_queue.get()
        if n == 'STOP':
            return
        random_numbers = np.random.rand(n)
        out_queue.put(random_numbers)

In [3]:
def generate_random_numbers(show_output, up_to):
    thread = threading.Thread(target=random_number_threading)
    thread.start()
    for i in range(up_to):
        in_queue.put(i)
        random_nums = out_queue.get()
        if show_output:
            print(random_nums)
    in_queue.put('STOP')
    thread.join()

In [4]:
generate_random_numbers(True, 10)


[]
[0.5488135]
[0.71518937 0.60276338]
[0.54488318 0.4236548  0.64589411]
[0.43758721 0.891773   0.96366276 0.38344152]
[0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
[0.0871293  0.0202184  0.83261985 0.77815675 0.87001215 0.97861834]
[0.79915856 0.46147936 0.78052918 0.11827443 0.63992102 0.14335329
 0.94466892]
[0.52184832 0.41466194 0.26455561 0.77423369 0.45615033 0.56843395
 0.0187898  0.6176355 ]
[0.61209572 0.616934   0.94374808 0.6818203  0.3595079  0.43703195
 0.6976312  0.06022547 0.66676672]


In [5]:
cProfile.run('generate_random_numbers(False, 20000)')


         740057 function calls in 15.894 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.247    0.247   15.879   15.879 <ipython-input-3-04f1b90debed>:1(generate_random_numbers)
        1    0.001    0.001   15.880   15.880 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 _weakrefset.py:38(_remove)
        1    0.000    0.000    0.000    0.000 _weakrefset.py:81(add)
    20001    0.296    0.000    1.194    0.000 queue.py:121(put)
    20000    0.577    0.000   14.382    0.001 queue.py:153(get)
    40000    0.157    0.000    0.237    0.000 queue.py:208(_qsize)
    20001    0.075    0.000    0.110    0.000 queue.py:212(_put)
    20000    0.075    0.000    0.107    0.000 queue.py:216(_get)
        1    0.000    0.000    0.000    0.000 threading.py:1017(_wait_for_tstate_lock)
        2    0.000    0.000    0.000    0.000 threading.py:1095(daemon)
        1    0.000    0.000    0.000    0.000 threa